/* eslint-disable no-console */
import { showLogger } from '@/constant/env';

type LogLevel = 'info' | 'warn' | 'error' | 'debug';

/**
 * A logger function that will only logs on development
 * @param object - The object to log
 * @param comment - Autogenerated with `lg` snippet
 */
export default function logger(object: unknown, comment?: string): void;

/**
 * Logger for server-side operations
 * @param message - The message to log
 * @param context - Optional context identifier
 * @param level - Log level
 */
export default function logger(
  message: string,
  context?: string,
  level?: LogLevel
): void;

export default function logger(
  messageOrObject: unknown,
  commentOrContext?: string,
  level?: LogLevel
): void {
  if (!showLogger && typeof window !== 'undefined') return;

  // Server-side logging
  if (typeof window === 'undefined') {
    const timestamp = new Date().toISOString();
    const context = commentOrContext || '';
    const logLevel = level || 'info';
    const prefix = context ? `[${context}]` : '';
    const logMessage = `${timestamp} ${prefix} ${messageOrObject}`;

    switch (logLevel) {
      case 'error':
        console.error(logMessage);
        break;
      case 'warn':
        console.warn(logMessage);
        break;
      case 'debug':
        console.debug(logMessage);
        break;
      default:
        console.log(logMessage);
    }
    return;
  }

  // Client-side logging (original behavior)
  console.log(
    '%c ============== INFO LOG \n',
    'color: #22D3EE',
    `${typeof window !== 'undefined' && window?.location.pathname}\n`,
    `=== ${commentOrContext ?? ''}\n`,
    messageOrObject
  );
}
