-- Seed data for The Red Stuff PWA
-- Run this after schema.sql

-- Insert quotes from Jesus's teachings
insert into public.quotes (id, text, reference, theme, tags, context) values
  ('quote-matthew-25-40', 
   'Truly I tell you, whatever you did for one of the least of these brothers and sisters of mine, you did for me.',
   'Matthew 25:40',
   'hunger',
   array['compassion', 'service', 'justice'],
   'Jesus teaches that caring for the vulnerable is caring for Him directly.'),
  
  ('quote-matthew-7-16',
   'By their fruits you will know them.',
   'Matthew 7:16',
   'community',
   array['action', 'character', 'witness'],
   'Discipleship is verified by tangible acts of mercy and justice.'),
  
  ('quote-matthew-5-9',
   'Blessed are the peacemakers, for they will be called children of God.',
   'Matthew 5:9',
   'peace',
   array['peace', 'justice', 'reconciliation'],
   'The Sermon on the Mount invites active peacemaking, not passive avoidance.'),
  
  ('quote-matthew-5-14',
   'You are the light of the world. A town built on a hill cannot be hidden... let your light shine before others.',
   'Matthew 5:14-16',
   'community',
   array['witness', 'community', 'action'],
   'Jesus calls His followers to live visibly transformative lives.'),
  
  ('quote-matthew-19-14',
   'Let the little children come to me... for the kingdom of heaven belongs to such as these.',
   'Matthew 19:14',
   'children',
   array['education', 'youth', 'care'],
   'Christ elevates the value and dignity of children and youth.'),
  
  ('quote-matthew-5-7',
   'Blessed are the merciful, for they will be shown mercy.',
   'Matthew 5:7',
   'mercy',
   array['mercy', 'compassion', 'prison'],
   'Mercy is reciprocal—God expects the forgiven to extend forgiveness.'),
  
  ('quote-matthew-5-4',
   'Blessed are those who mourn, for they will be comforted.',
   'Matthew 5:4',
   'hope',
   array['hope', 'grief', 'care'],
   'Jesus promises presence and comfort amid grief and loss.'),
  
  ('quote-luke-4-18',
   'The Spirit of the Lord is on me... He has sent me to proclaim freedom for the prisoners and recovery of sight for the blind.',
   'Luke 4:18',
   'justice',
   array['justice', 'prison', 'freedom'],
   'Jesus frames His ministry around liberation for the marginalized.'),
  
  ('quote-matthew-28-19',
   'Go and make disciples of all nations... teaching them to obey everything I have commanded you.',
   'Matthew 28:19-20',
   'faith',
   array['faith', 'mission', 'teaching'],
   'The Great Commission ties learning to living.'),
  
  ('quote-luke-10-9',
   'Heal the sick who are there and tell them, "The kingdom of God has come near to you."',
   'Luke 10:9',
   'healthcare',
   array['healing', 'healthcare', 'hope'],
   'The disciples tie tangible healing to spiritual hope.'),
  
  ('quote-matthew-5-6',
   'Blessed are those who hunger and thirst for righteousness, for they will be filled.',
   'Matthew 5:6',
   'justice',
   array['justice', 'advocacy', 'equity'],
   'Jesus links justice-seeking with God''s satisfaction.'),
  
  ('quote-matthew-9-37',
   'The harvest is plentiful but the workers are few.',
   'Matthew 9:37',
   'community',
   array['service', 'calling', 'mission'],
   'Opportunity abounds, but laborers must step forward.'),
  
  ('quote-john-13-34',
   'Love one another. As I have loved you, so you must love one another.',
   'John 13:34',
   'family',
   array['love', 'community', 'care'],
   'Jesus roots action in self-giving love.')
on conflict (id) do nothing;

-- Insert sample volunteer opportunities
insert into public.opportunities (
  id, organization_name, organization_type, opportunity_title, description,
  time_commitment, location, skills_needed, cause_categories, related_quotes,
  urgency_level, contact_info, website_url, verified_status, active_status, image_url, highlight_reason
) values
  ('op-001',
   'City Shelter Alliance',
   'charity',
   'Winter Emergency Shelter Volunteers',
   'Help provide warm meals and overnight shelter support during winter storm season. Volunteers assist with intake, meal service, and creating a welcoming environment for guests experiencing homelessness.',
   'weekly',
   '{"city": "Chicago", "state": "IL", "country": "USA", "mode": "local"}'::jsonb,
   array['Communication', 'Empathy', 'Physical stamina'],
   array['homelessness', 'hunger', 'community'],
   array['quote-matthew-25-40'],
   'immediate',
   '{"name": "Sarah Martinez", "email": "volunteers@cityshelter.org", "phone": "(312) 555-0100"}'::jsonb,
   'https://cityshelteralliance.org',
   true,
   true,
   null,
   'Urgent need during severe winter weather'),
  
  ('op-002',
   'Meals on Wheels Chicago',
   'charity',
   'Meal Delivery Driver',
   'Deliver hot, nutritious meals to homebound seniors and individuals with disabilities. Routes take 2-3 hours and include friendly wellness checks that may be the only human contact recipients have all day.',
   'weekly',
   '{"city": "Chicago", "state": "IL", "country": "USA", "mode": "local"}'::jsonb,
   array['Valid driver''s license', 'Reliable vehicle', 'Compassion'],
   array['elderly', 'hunger', 'healthcare'],
   array['quote-matthew-25-40', 'quote-john-13-34'],
   'ongoing',
   '{"email": "volunteer@mowchicago.org", "phone": "(312) 555-0200"}'::jsonb,
   'https://mealsonwheelschicago.org',
   true,
   true,
   null,
   'Critical service for isolated seniors'),
  
  ('op-003',
   'Reading Partners',
   'education',
   'Elementary Reading Tutor',
   'Provide one-on-one reading support to students in grades K-4 who are reading below grade level. All curriculum and training provided. Make a lasting impact on a child''s educational journey.',
   'weekly',
   '{"city": "Multiple locations", "state": "Nationwide", "country": "USA", "mode": "hybrid"}'::jsonb,
   array['Patience', 'Consistency', 'Communication'],
   array['education', 'children', 'youth'],
   array['quote-matthew-19-14', 'quote-matthew-9-37'],
   'ongoing',
   '{"email": "volunteer@readingpartners.org"}'::jsonb,
   'https://readingpartners.org/volunteer',
   true,
   true,
   null,
   'Virtual and in-person options available'),
  
  ('op-004',
   'Prison Fellowship',
   'church',
   'Pen Pal Program Correspondent',
   'Write encouraging letters to incarcerated individuals seeking connection and hope. Share your faith, provide encouragement, and help break the isolation of incarceration through meaningful correspondence.',
   'monthly',
   '{"mode": "remote"}'::jsonb,
   array['Writing', 'Empathy', 'Consistency'],
   array['prison', 'justice', 'community'],
   array['quote-luke-4-18', 'quote-matthew-5-7'],
   'ongoing',
   '{"email": "volunteer@prisonfellowship.org"}'::jsonb,
   'https://www.prisonfellowship.org/about/angel-tree/volunteer/',
   true,
   true,
   null,
   'Make a difference from anywhere'),
  
  ('op-005',
   'Ronald McDonald House',
   'charity',
   'Family Support Volunteer',
   'Provide comfort and support to families with children receiving medical treatment. Help with meals, childcare, or simply offer a listening ear during difficult times.',
   'monthly',
   '{"city": "Multiple locations", "state": "Nationwide", "country": "USA", "mode": "local"}'::jsonb,
   array['Compassion', 'Reliability', 'Flexibility'],
   array['healthcare', 'family', 'children'],
   array['quote-luke-10-9', 'quote-matthew-5-4'],
   'ongoing',
   '{"email": "volunteer@rmhc.org"}'::jsonb,
   'https://www.rmhc.org/get-involved',
   true,
   true,
   null,
   'Support families in their darkest hours'),
  
  ('op-006',
   'Big Brothers Big Sisters',
   'charity',
   'Youth Mentor',
   'Become a positive role model and friend to a young person facing adversity. Spend time together, share activities, and help them reach their potential through consistent, caring relationship.',
   'weekly',
   '{"city": "Nationwide", "state": "USA", "country": "USA", "mode": "local"}'::jsonb,
   array['Commitment', 'Patience', 'Positive role modeling'],
   array['youth', 'education', 'community'],
   array['quote-matthew-19-14', 'quote-matthew-5-14'],
   'ongoing',
   '{"email": "volunteer@bbbs.org"}'::jsonb,
   'https://www.bbbs.org/become-a-volunteer/',
   true,
   true,
   null,
   '1-year commitment transforms lives'),
  
  ('op-007',
   'Ocean Conservancy',
   'environmental',
   'Beach Cleanup Coordinator',
   'Lead monthly beach cleanup events to remove plastic and debris from coastal areas. Help protect marine life and raise awareness about ocean conservation in your community.',
   'monthly',
   '{"city": "Coastal cities", "state": "Nationwide", "country": "USA", "mode": "local"}'::jsonb,
   array['Leadership', 'Organization', 'Environmental passion'],
   array['environment', 'community'],
   array['quote-matthew-5-14'],
   'seasonal',
   '{"email": "volunteer@oceanconservancy.org"}'::jsonb,
   'https://oceanconservancy.org/trash-free-seas/international-coastal-cleanup/volunteer/',
   true,
   true,
   null,
   'Peak season: Spring and Summer'),
  
  ('op-008',
   'Habitat for Humanity',
   'charity',
   'Home Construction Volunteer',
   'Help build affordable housing for families in need. No construction experience required—training provided. Work alongside future homeowners to create safe, decent places to live.',
   'one-time',
   '{"city": "Nationwide", "state": "USA", "country": "USA", "mode": "local"}'::jsonb,
   array['Physical stamina', 'Teamwork', 'Willingness to learn'],
   array['homelessness', 'community', 'family'],
   array['quote-matthew-25-40', 'quote-matthew-7-16'],
   'ongoing',
   '{"email": "volunteer@habitat.org"}'::jsonb,
   'https://www.habitat.org/volunteer',
   true,
   true,
   null,
   'Build days every Saturday'),
  
  ('op-009',
   'Khan Academy',
   'education',
   'Online Math Tutor',
   'Provide free math tutoring to students worldwide through video calls. Help students master concepts from basic arithmetic to calculus. Flexible scheduling and all materials provided.',
   'weekly',
   '{"mode": "remote"}'::jsonb,
   array['Math proficiency', 'Teaching ability', 'Patience'],
   array['education', 'youth', 'children'],
   array['quote-matthew-19-14', 'quote-matthew-9-37'],
   'ongoing',
   '{"email": "tutors@khanacademy.org"}'::jsonb,
   'https://www.khanacademy.org',
   true,
   true,
   null,
   'Impact students globally from home'),
  
  ('op-010',
   'The Nature Conservancy',
   'environmental',
   'Trail Maintenance Volunteer',
   'Help maintain and restore hiking trails in local nature preserves. Remove invasive species, repair erosion, and ensure trails remain accessible for all to enjoy nature.',
   'monthly',
   '{"city": "Nationwide", "state": "USA", "country": "USA", "mode": "local"}'::jsonb,
   array['Physical fitness', 'Outdoor skills', 'Environmental stewardship'],
   array['environment', 'community'],
   array['quote-matthew-5-14'],
   'seasonal',
   '{"email": "volunteer@nature.org"}'::jsonb,
   'https://www.nature.org/en-us/get-involved/how-to-help/volunteer/',
   true,
   true,
   null,
   'Best in Spring and Fall'),
  
  ('op-011',
   'American Red Cross',
   'charity',
   'Disaster Response Volunteer',
   'Respond to local disasters like house fires and floods. Provide immediate assistance to families who have lost everything, including emergency shelter, food, and emotional support.',
   'on-call',
   '{"city": "Nationwide", "state": "USA", "country": "USA", "mode": "local"}'::jsonb,
   array['Flexibility', 'Crisis management', 'Compassion', 'Available on short notice'],
   array['community', 'healthcare', 'family'],
   array['quote-matthew-5-4', 'quote-luke-10-9'],
   'immediate',
   '{"email": "volunteer@redcross.org", "phone": "1-800-RED-CROSS"}'::jsonb,
   'https://www.redcross.org/volunteer/become-a-volunteer.html',
   true,
   true,
   null,
   'Urgent need for on-call volunteers'),
  
  ('op-012',
   'Community Food Bank',
   'charity',
   'Food Distribution Assistant',
   'Sort, pack, and distribute food to families facing hunger. Work in warehouse or at mobile distribution sites. Every shift helps feed dozens of families in your community.',
   'weekly',
   '{"city": "Multiple locations", "state": "Nationwide", "country": "USA", "mode": "local"}'::jsonb,
   array['Physical stamina', 'Teamwork', 'Reliability'],
   array['hunger', 'community', 'family'],
   array['quote-matthew-25-40', 'quote-matthew-7-16'],
   'ongoing',
   '{"email": "volunteer@communityfoodbank.org"}'::jsonb,
   'https://communityfoodbank.org/volunteer',
   true,
   true,
   null,
   'Food insecurity is at record high')
on conflict (id) do nothing;

-- Insert sample current events
insert into public.news_events (
  id, external_id, headline, summary, source, category, region, published_at,
  related_quote_ids, related_opportunity_ids
) values
  ('event-homelessness-urban',
   'news-2025-01-15-001',
   'Urban centers report record homelessness during winter storms',
   'Shelters in the Midwest and Northeast are operating at 115% capacity amid sub-zero wind chills.',
   'Associated Press',
   'homelessness',
   'United States',
   '2025-01-15T08:00:00Z',
   array['quote-matthew-25-40'],
   array['op-001', 'op-002', 'op-012']),
  
  ('event-education-gap',
   'news-2025-01-11-002',
   'Reading scores lag two grade levels for low-income elementary students',
   'Districts cite volunteer shortages, with 600+ virtual tutoring slots remaining empty nationwide.',
   'Education Week',
   'education',
   'United States',
   '2025-01-11T09:00:00Z',
   array['quote-matthew-19-14', 'quote-matthew-9-37'],
   array['op-003', 'op-009']),
  
  ('event-water-quality',
   'news-2025-01-09-003',
   'Microplastics surge in coastal waterways following extreme rains',
   'Environmental scientists urge rapid cleanup efforts before spring salmon migration in the Pacific Northwest.',
   'Environmental Science News',
   'environment',
   'Pacific Northwest',
   '2025-01-09T12:00:00Z',
   array['quote-matthew-5-14'],
   array['op-007', 'op-010']),
  
  ('event-hospital-capacity',
   'news-2025-01-18-004',
   'Regional hospitals seek more family support volunteers',
   'Nurses spend up to 30% of their shift coordinating family needs amid respiratory illness surge.',
   'Healthcare Today',
   'healthcare',
   'Southeast',
   '2025-01-18T14:00:00Z',
   array['quote-luke-10-9', 'quote-matthew-5-4'],
   array['op-005', 'op-011'])
on conflict (id) do nothing;

-- Create a sample daily feature
insert into public.daily_features (
  feature_date, featured_event_id, featured_quote_id, featured_opportunity_id, reflection, active
) values
  (current_date,
   'event-homelessness-urban',
   'quote-matthew-25-40',
   'op-001',
   'When the news shows rising homelessness, Jesus reminds us that serving "the least of these" is serving Him. The City Shelter Alliance needs you this week—your presence matters as much as your service.',
   true)
on conflict (feature_date) do nothing;
